# fly.toml app configuration file generated for flashcard-backend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "flashcard-backend"
primary_region = "cdg"  # Paris

[build]
  dockerfile = "Dockerfile"

[env]
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "30"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
