"""Add game_sessions table

Revision ID: 1974e6bd878b
Revises: fae5b3aa8ff6
Create Date: 2025-12-24 17:01:38.042182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1974e6bd878b'
down_revision: Union[str, None] = 'fae5b3aa8ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create game_sessions table (other tables already exist)
    op.create_table('game_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('deck_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='gamesessionstatus'), nullable=False),
    sa.Column('remaining_cards', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('success_cards', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard.decks.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flashcard.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcard'
    )
    op.create_index(op.f('ix_flashcard_game_sessions_id'), 'game_sessions', ['id'], unique=False, schema='flashcard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop game_sessions table
    op.drop_index(op.f('ix_flashcard_game_sessions_id'), table_name='game_sessions', schema='flashcard')
    op.drop_table('game_sessions', schema='flashcard')
    op.execute('DROP TYPE gamesessionstatus')
    # ### end Alembic commands ###

