"""initial schema with all tables

Revision ID: fae5b3aa8ff6
Revises: 
Create Date: 2025-12-24 14:45:31.914836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae5b3aa8ff6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['flashcard.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcard'
    )
    op.create_index(op.f('ix_flashcard_users_id'), 'users', ['id'], unique=False, schema='flashcard')
    op.create_index(op.f('ix_flashcard_users_username'), 'users', ['username'], unique=True, schema='flashcard')
    op.create_table('decks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['flashcard.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcard'
    )
    op.create_index(op.f('ix_flashcard_decks_id'), 'decks', ['id'], unique=False, schema='flashcard')
    op.create_table('cards',
    sa.Column('deck_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard.decks.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['flashcard.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcard'
    )
    op.create_index(op.f('ix_flashcard_cards_id'), 'cards', ['id'], unique=False, schema='flashcard')
    op.create_table('user_progress',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('deck_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flashcard.cards.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard.decks.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['flashcard.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flashcard.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcard'
    )
    op.create_index(op.f('ix_flashcard_user_progress_id'), 'user_progress', ['id'], unique=False, schema='flashcard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcard_user_progress_id'), table_name='user_progress', schema='flashcard')
    op.drop_table('user_progress', schema='flashcard')
    op.drop_index(op.f('ix_flashcard_cards_id'), table_name='cards', schema='flashcard')
    op.drop_table('cards', schema='flashcard')
    op.drop_index(op.f('ix_flashcard_decks_id'), table_name='decks', schema='flashcard')
    op.drop_table('decks', schema='flashcard')
    op.drop_index(op.f('ix_flashcard_users_username'), table_name='users', schema='flashcard')
    op.drop_index(op.f('ix_flashcard_users_id'), table_name='users', schema='flashcard')
    op.drop_table('users', schema='flashcard')
    # ### end Alembic commands ###

